In [3]:
import tensorflow as tf
import numpy as np

In [9]:
data_x = np.array([[0,0],[0,1],[1,0],[1,1]],dtype=np.float32)
data_y = np.array([[0],[1],[1],[0]],dtype=np.float32)

In [6]:
x = tf.placeholder(tf.float32,shape=[None,2],name='input')
w1 = tf.Variable(tf.random_uniform([2,4],-1,1),name='w1')
b1 = tf.Variable(tf.zeros(4,dtype=np.float32),name='b1')
w2 = tf.Variable(tf.random_uniform([4,1],-1,1),name='w2')
b2 = tf.Variable(tf.zeros(1,dtype=np.float32),name='b2')
y = tf.placeholder(tf.float32,shape=[None,1],name='output')
z1 = tf.sigmoid(tf.matmul(x,w1)+b1)
z2 = tf.sigmoid(tf.matmul(z1,w2)+b2)
loss=tf.nn.l2_loss(z2-y)
opt = tf.train.GradientDescentOptimizer(0.05)
train_op = opt.minimize(loss)

In [31]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for iter in range(10000):
        loss_val=sess.run([loss,train_op],feed_dict={x:data_x,y:data_y})
        if iter % 1000 == 0:
            print iter,"loss=",loss_val
            print sess.run(w1)

0 loss= [0.50439954, None]
[[-0.73339033  0.9333019   0.8838294   0.9742164 ]
 [ 0.6890396  -0.45273435  0.15522268 -0.806306  ]]
1000 loss= [0.49914864, None]
[[-0.7415917   0.7820928   0.88717324  0.9769878 ]
 [ 0.6846562  -0.47553328 -0.11208697 -0.8045873 ]]
2000 loss= [0.495026, None]
[[-0.76177675  0.7779411   0.9501099   0.99731076]
 [ 0.67430043 -0.70698446 -0.2965814  -0.7945441 ]]
3000 loss= [0.47955593, None]
[[-0.79913616  1.052095    1.1001599   1.0370246 ]
 [ 0.6705604  -1.2066892  -0.52176034 -0.78689915]]
4000 loss= [0.40823883, None]
[[-0.89145595  1.893031    1.4668812   1.1308938 ]
 [ 0.72675097 -2.1338944  -0.9726103  -0.82527655]]
5000 loss= [0.22952883, None]
[[-1.1344863  3.095024   2.2341774  1.32851  ]
 [ 1.0094812 -3.268392  -1.9038008 -1.0329036]]
6000 loss= [0.09413818, None]
[[-1.453791   3.9351604  2.972461   1.5182399]
 [ 1.3658881 -4.0301566 -2.734905  -1.2607607]]
7000 loss= [0.046312798, None]
[[-1.6966416  4.375435   3.391885   1.6327928]
 [ 1.6055942

In [33]:
print w1.name
print b1.name

w1_2:0
b1_2:0
